CREATE TABLE IF NOT EXISTS `Users`(
    UserId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(25),
    Position VARCHAR(25),
    Username VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL
);
